name: Update PR Description
author: collective-hub
description: Add or update content in GitHub PR description.

inputs:
  prNumber:
    description: The PR number to update. If this isn't provided, it will try to be inferred from the PR number provided in the `pull_request` event, or from the commit SHA.
    required: true
  content:
    description: Content to append or replace in the PR body.
    required: true
  contentIsFilePath:
    description: Whether the content is a file path.
    required: false
  regex:
    description: Regex string to match and replace with content.
    required: false
  regexFlags:
    description: Regex flags to use.
    required: false
  appendContentOnMatchOnly:
    description: Whether to skip appending the content to the PR body if no regex matches are found.
    default: "false"
  token:
    description: GitHub access token.
    required: true

runs:
  using: node20
  main: dist/index.js

branding:
  icon: align-left
  color: white
